### ISSUE TITLE
Stacks 1.37 php access not working

### ISSUE THREAD

**Issue by BELKHIR** [pseudogene/docker-stacks#1]
Dear all,

The Stacks version 1.37  (Feb 24, 2016) have this new feature :
"converted PHP database code from MDB2 to MySQLi. MDB2 is no longer a prerequisite for installing Stacks". 
So the php scripts provided by Stacks needs mysqli extention which is not installed in docker-stacks:gui image.

Thank's for this job !

**Comment by pseudogene** [comment]
Well spotted. I updated to 1.37 without checking.
I fixed (and tested) the installation script.
M
